name: race_room
description: "F1 Information App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.5.1+1200

environment:
  sdk: '>=3.4.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_floating_bottom_bar: ^1.2.1+1
  http: ^1.2.2
  logger: ^2.4.0
  diacritic: ^0.1.6
  intl: ^0.20.1
  package_info_plus: ^8.1.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.2
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.1
  widget_zoom: ^0.0.4
  path_provider: ^2.1.5
  flutter_pdfview: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/f1car.png
     - assets/images/racing-helmet.png
     - assets/images/f1car-white.png
     - assets/images/racing-helmet-white.png
     - assets/images/rhb.png
     - assets/images/rhw.png
     - assets/images/carf1b.png
     - assets/images/carf1w.png
     - assets/images/img_not_found.jpg
     - assets/images/track_error.png
     - assets/images/track_error_w.png
     - assets/images/rr_app_logo_2.png
     - assets/images/ds-dark.png
     - assets/images/ds-light.png
     - assets/images/ts-dark.png
     - assets/images/ts-light.png
     - assets/images/rr_splash.png
     - assets/images/telemetry-icon.png
     - assets/images/telemetry-icon-dark.png
     - assets/images/ic_launcher_android.png

     - assets/f1Tracks/Abu_Dhabi_Circuit.png
     - assets/f1Tracks/Australia_Circuit.png
     - assets/f1Tracks/Austria_Circuit.png
     - assets/f1Tracks/Bahrain_Circuit.png
     - assets/f1Tracks/Baku_Circuit.png
     - assets/f1Tracks/Belgium_Circuit.png
     - assets/f1Tracks/Brazil_Circuit.png
     - assets/f1Tracks/Canada_Circuit.png
     - assets/f1Tracks/China_Circuit.png
     - assets/f1Tracks/Emilia_Romagna_Circuit.png
     - assets/f1Tracks/Great_Britain_Circuit.png
     - assets/f1Tracks/Hungary_Circuit.png
     - assets/f1Tracks/Italy_Circuit.png
     - assets/f1Tracks/Japan_Circuit.png
     - assets/f1Tracks/Las_Vegas_Circuit.png
     - assets/f1Tracks/Mexico_Circuit.png
     - assets/f1Tracks/Miami_Circuit.png
     - assets/f1Tracks/Monaco_Circuit.png
     - assets/f1Tracks/Netherlands_Circuit.png
     - assets/f1Tracks/Qatar_Circuit.png
     - assets/f1Tracks/Saudi_Arabia_Circuit.png
     - assets/f1Tracks/Singapore_Circuit.png
     - assets/f1Tracks/Spain_Circuit.png
     - assets/f1Tracks/USA_Circuit.png
     - assets/f1Tracks/Russia_Circuit.png
     - assets/f1Tracks/Sepang_Circuit.png
     - assets/f1Tracks/Tuscany_Circuit.png
     - assets/f1Tracks/Portugal_Circuit.png
     - assets/f1Tracks/Nurburgring_Circuit.png
     - assets/f1Tracks/Turkey_Circuit.png
     - assets/f1Tracks/Germany_Circuit_Hockenheim.png
     - assets/f1Tracks/Fuji_Circuit.png
     - assets/f1Tracks/Valencia_Circuit.png
     - assets/f1Tracks/India_Circuit.png
     - assets/f1Tracks/Korea_Circuit.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Formula1
       fonts:
         - asset: assets/fonts/Formula1-Regular_web_0.ttf
         - asset: assets/fonts/Formula1-Bold_web_0.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  image: "assets/images/rr_splash_ios.png"
  color: "#FF3131"

  android_12:
    image: "assets/images/rr_splash_android.png"
    color: "#FF3131"

flutter_launcher_icons:
  image_path_android: "assets/images/ic_launcher_android.png"
  image_path_ios: "assets/images/rr_app_logo_2.png"
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21

  web:
    generate: true
    image_path: "assets/images/rr_app_logo_2.png"
    background_color: "#FF0000"
    theme_color: "#FF0000"
  windows:
    generate: true
    image_path: "assets/images/rr_app_logo_2.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/rr_app_logo_2.png"